# Generated by Django 3.0 on 2019-12-16 08:36

from django.conf import settings
import django.core.files.storage
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.CharField(default='', max_length=100)),
                ('city', models.CharField(default='', max_length=25)),
                ('mobile', models.CharField(blank=True, default='', max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be of 10 digits', regex='^\\d{10}$')])),
                ('driving_licence', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='D:\\ChampionzArena\\championzarena\\DOCS'), upload_to='uploads/driving_licence/DL14-06-31')),
                ('pancard', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='D:\\ChampionzArena\\championzarena\\DOCS'), upload_to='uploads/pancard/pancard14-06-31')),
                ('is_driving_licence_verified', models.BooleanField()),
                ('is_pancard_verified', models.BooleanField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
