# Generated by Django 3.0 on 2019-12-16 08:36

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('f_name', models.CharField(help_text="Player's First Name", max_length=50, primary_key=True, serialize=False, verbose_name='First Name')),
                ('m_name', models.CharField(help_text="Player's Middle Name", max_length=50, verbose_name='Middle Name')),
                ('l_name', models.CharField(help_text="Player's Last Name", max_length=50, verbose_name='Last Name')),
                ('pic', models.ImageField(default='/default_player_pic.jpg', upload_to='player_pic')),
                ('age', models.IntegerField(help_text="Player's age")),
                ('dob', models.DateField(default=datetime.date.today)),
                ('nationality', models.CharField(choices=[('NN', 'None'), ('afg', 'Afghanistan'), ('aus', 'Australia'), ('bng', 'Bangladesh'), ('eng', 'England'), ('ind', 'India'), ('irl', 'Ireland'), ('nz', 'New Zealand'), ('pak', 'Pakistan'), ('sl', 'Sri Lanka'), ('saf', 'South Africa'), ('wi', 'West Indies'), ('zim', 'Zimbabwe')], default='None', max_length=3, verbose_name='Nationality')),
                ('is_batsman', models.BooleanField(default=False)),
                ('is_bowler', models.BooleanField(default=False)),
                ('is_keeper', models.BooleanField(default=False)),
                ('value', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(11.0)])),
            ],
        ),
        migrations.CreateModel(
            name='Nation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_flag', models.FilePathField(path='/country_flags')),
                ('nation_player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='players.Player')),
            ],
            options={
                'ordering': ['country_flag'],
            },
        ),
    ]
