# Generated by Django 3.0 on 2019-12-16 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='country_flag',
            field=models.FilePathField(default='country_flags/default_player_pic.jpg', match='nation.*\\.jpeg$', path='/country_flags'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Nation',
        ),
    ]
